In [150]:
import requests
import pandas as pd

# URL de l'API
url = "https://db.ygoprodeck.com/api/v7/cardinfo.php"

# Faire une requête à l'API
response = requests.get(url)
data = response.json()

# Initialiser une liste pour stocker les données transformées
expanded_data = []

# Parcourir chaque carte dans les données
for card in data['data']:
    # Vérifier si la carte a des sets
    if 'card_sets' in card:
        for card_set in card['card_sets']:
            # Ajouter une ligne pour chaque set
            expanded_data.append({
                'id': card['id'],
                'name': card['name'],
                'set_name': card_set['set_name'],
                'set_code': card_set['set_code'],
                'set_rarity': card_set['set_rarity']
            })
    else:
        # Si la carte n'a pas de sets, ajouter une seule ligne sans information de set
        expanded_data.append({
            'id': card['id'],
            'name': card['name'],
            'set_name': None,
            'set_code': None,
            'set_rarity': None
        })

# Convertir les données en DataFrame
df = pd.DataFrame(expanded_data)
df

,id,name,set_name,set_code,set_rarity
0,34541863,"""A"" Cell Breeding Device",Force of the Breaker,FOTB-EN043,Common
1,64163367,"""A"" Cell Incubator",Gladiator's Assault,GLAS-EN062,Common
2,91231901,"""A"" Cell Recombination Device",Invasion: Vengeance,INOV-EN063,Common
3,73262676,"""A"" Cell Scatter Burst",Strike of Neos,STON-EN041,Common
4,98319530,"""Infernoble Arms - Almace""",Duelist Nexus,DUNE-EN056,Quarter Century Secret Rare
...,...,...,...,...,...
37235,18865703,ZW - Ultimate Shield,King's Court,KICO-EN036,Rare
37236,76080032,ZW - Unicorn Spear,Order of Chaos,ORCS-EN005,Rare
37237,76080032,ZW - Unicorn Spear,Star Pack 2014,SP14-EN004,Common
37238,76080032,ZW - Unicorn Spear,Star Pack 2014,SP14-EN004,Starfoil Rare
37239,76080032,ZW - Unicorn Spear,Super Starter: V for Victory,YS13-EN018,Common

In [151]:
# Number of unique card
len(df['id'].unique())

13191

In [152]:
# Enregistrer dans un fichier Excel de la liste des cartes
df.to_excel('yugioh_collection_retrieved.xlsx', index=False)

print("Fichier Excel généré avec succès!")

Fichier Excel généré avec succès!

In [153]:
# Comparaison avec le fichier collection rempli de base
df_collection = pd.read_excel('d:/Projets/Code/Python/Yu-Gi-Oh-Collection/yugioh_collection_fullfiled.xlsx')
df_collection

,id,name,set_name,set_code,set_rarity,qty_set,qty_collection
0,34541863,"""A"" Cell Breeding Device",Force of the Breaker,FOTB-EN043,Common,NaN,0
1,64163367,"""A"" Cell Incubator",Gladiator's Assault,GLAS-EN062,Common,NaN,0
2,91231901,"""A"" Cell Recombination Device",Invasion: Vengeance,INOV-EN063,Common,NaN,0
3,73262676,"""A"" Cell Scatter Burst",Strike of Neos,STON-EN041,Common,NaN,0
4,98319530,"""Infernoble Arms - Almace""",Duelist Nexus,DUNE-EN056,Quarter Century Secret Rare,NaN,0
...,...,...,...,...,...,...,...
37225,45082499,ZW - Lightning Blade,Cosmo Blazer,CBLZ-EN005,Rare,NaN,0
37226,32164201,ZW - Pegasus Twin Saber,Lightning Overdrive,LIOV-EN001,Common,NaN,0
37227,32164201,ZW - Pegasus Twin Saber,2022 Tin of the Pharaoh's Gods,MP22-EN057,Super Rare,NaN,0
37228,87008374,ZW - Phoenix Bow,Return of the Duelist,REDU-EN003,Rare,NaN,0
37229,2648201,ZW - Sleipnir Mail,Primal Origin,PRIO-EN096,Common,NaN,0

In [154]:
df_collection.shape

(37230, 7)

In [155]:
# Sélectionner les colonnes pertinentes pour la comparaison
columns_to_compare = ['id', 'name', 'set_name', 'set_code', 'set_rarity']

# Créer un DataFrame en supprimant les lignes de df qui sont dans df_collection
df_cards_to_add = df.merge(df_collection[columns_to_compare], on=columns_to_compare, how='left', indicator=True)
df_cards_to_add = df_cards_to_add[df_cards_to_add['_merge'] == 'left_only'].drop(columns=['_merge'])

df_cards_to_add

,id,name,set_name,set_code,set_rarity
36983,33744268,Z-Zillion Tank,None,None,None
37231,95886782,ZW - Sylphid Wing,Brothers of Legend,BROL-EN025,Ultra Rare
37232,81471108,ZW - Tornado Bringer,Cosmo Blazer,CBLZ-EN006,Rare
37233,81471108,ZW - Tornado Bringer,King's Court,KICO-EN035,Rare
37234,18865703,ZW - Ultimate Shield,Cosmo Blazer,CBLZ-EN007,Common
37235,18865703,ZW - Ultimate Shield,King's Court,KICO-EN036,Rare
37236,76080032,ZW - Unicorn Spear,Order of Chaos,ORCS-EN005,Rare
37237,76080032,ZW - Unicorn Spear,Star Pack 2014,SP14-EN004,Common
37238,76080032,ZW - Unicorn Spear,Star Pack 2014,SP14-EN004,Starfoil Rare
37239,76080032,ZW - Unicorn Spear,Super Starter: V for Victory,YS13-EN018,Common

In [156]:
# Vérifier qu'aucune des cartes à ajouter
# ne figure dans la collection
df_common = df_cards_to_add.merge(df_collection[columns_to_compare], on=columns_to_compare, how='inner')
df_common

Empty DataFrame
Columns: [id, name, set_name, set_code, set_rarity]
Index: []

In [157]:
# Enregistrer le DataFrame résultant dans un fichier Excel
df_cards_to_add.to_excel('d:/Projets/Code/Python/Yu-Gi-Oh-Collection/data_to_add/df_cards_to_add.xlsx', index=False)

print("Fichier df_cards_to_add.xlsx généré avec succès!")

Fichier df_cards_to_add.xlsx généré avec succès!

In [158]:
r = requests.get('https://db.ygoprodeck.com/api/v7/cardsets.php')
r.json()

data = r.json()

# Créer un DataFrame pandas
df_unique_sets = pd.DataFrame(data)
df_unique_sets

,set_name,set_code,num_of_cards,tcg_date,set_image
0,2-Player Starter Deck: Yuya & Declan,YS15,42,2015-05-28,https://images.ygoprodeck.com/images/sets/YS15...
1,2-Player Starter Set,STAS,88,2024-01-26,NaN
2,2013 Collectible Tins Wave 1,CT10,9,2013-08-30,https://images.ygoprodeck.com/images/sets/CT10...
3,2013 Collectible Tins Wave 2,CT10,9,2013-11-22,https://images.ygoprodeck.com/images/sets/CT10...
4,2014 Mega-Tin Mega Pack,MP14,247,2014-08-28,https://images.ygoprodeck.com/images/sets/MP14...
...,...,...,...,...,...
970,Yugi & Kaiba Collector Box,KACB,1,2018-03-29,https://images.ygoprodeck.com/images/sets/KACB...
971,Yugi's Collector Box,YUCB,1,2017-09-15,https://images.ygoprodeck.com/images/sets/YUCB...
972,Yugi's Legendary Decks,YGLD,126,2015-11-12,https://images.ygoprodeck.com/images/sets/YGLD...
973,Zexal Collection Tin,ZTIN,24,2013-03-07,https://images.ygoprodeck.com/images/sets/ZTIN...
974,Zombie World Structure Deck,SDZW,37,2008-10-21,https://images.ygoprodeck.com/images/sets/SDZW...

In [159]:
# Enregistrer dans un fichier Excel de la liste des sets
df_unique_sets.to_excel('yugioh_collection_retrieved_sets.xlsx', index=False)

print("Fichier Excel généré avec succès!")

Fichier Excel généré avec succès!

In [160]:
# Comparaison avec le fichier collection rempli de base
sets_collection = pd.read_excel('d:/Projets/Code/Python/Yu-Gi-Oh-Collection/yugioh_collection_fullfiled.xlsx', sheet_name = 'sets')
sets_collection

,set_name,set_code,num_of_cards,tcg_date,set_image
0,Battles of Legend: Terminal Revenge,BLTR,117,0000-00-00,https://images.ygoprodeck.com/images/sets/BLTR...
1,OTS Tournament Pack 25,OP25,27,0000-00-00,https://images.ygoprodeck.com/images/sets/OP25...
2,The Lost Art Promotion 2024 B,LART,1,0000-00-00,https://images.ygoprodeck.com/images/sets/LART...
3,Summoned Skull Sample promotional card,SDY,1,2001-01-01,https://images.ygoprodeck.com/images/sets/SDY.jpg
4,Legend of Blue Eyes White Dragon,LOB,355,2002-03-08,https://images.ygoprodeck.com/images/sets/LOB.jpg
...,...,...,...,...,...
960,OTS Tournament Pack 23,OP23,27,2023-10-25,https://images.ygoprodeck.com/images/sets/OP23...
961,25th Anniversary Rarity Collection,RA01,78,2023-11-02,https://images.ygoprodeck.com/images/sets/RA01...
962,Valiant Smashers,VASM,60,2023-11-16,https://images.ygoprodeck.com/images/sets/VASM...
963,Structure Deck: Fire Kings,SR14,48,2023-12-07,https://images.ygoprodeck.com/images/sets/SR14...
964,Maze of Millennia,MZMI,85,2024-01-18,https://images.ygoprodeck.com/images/sets/MZMI...

In [161]:
sets_collection.shape

(965, 5)

In [162]:
# Sélectionner les colonnes pertinentes pour la comparaison
columns_to_compare_sets = ['set_name', 'set_code', 'num_of_cards', 'tcg_date']

# Créer un DataFrame en supprimant les lignes de df qui sont dans df_collection
df_sets_to_add = df_unique_sets.merge(sets_collection[columns_to_compare_sets], on=columns_to_compare_sets, how='left', indicator=True)
df_sets_to_add = df_sets_to_add[df_sets_to_add['_merge'] == 'left_only'].drop(columns=['_merge'])

df_sets_to_add

,set_name,set_code,num_of_cards,tcg_date,set_image
1,2-Player Starter Set,STAS,88,2024-01-26,NaN
23,25th Anniversary Ultimate Kaiba Set,KC01,62,2024-03-01,NaN
30,Adidas collaboration card,ADC1,1,2024-02-14,NaN
54,Battles of Legend: Chapter 1,BLC1,163,2024-02-22,https://images.ygoprodeck.com/images/sets/BLC1...
351,Legacy of Destruction,LEDE,86,2024-04-25,https://images.ygoprodeck.com/images/sets/LEDE...
452,OTS Tournament Pack 24,OP24,27,2024-02-14,https://images.ygoprodeck.com/images/sets/OP24...
470,Phantom Nightmare,PHNI,101,2024-02-08,https://images.ygoprodeck.com/images/sets/PHNI...
719,The Lost Art Promotion (series),LART,62,2024-02-14,https://images.ygoprodeck.com/images/sets/LART...
755,The Lost Art Promotion 2023 G,LART,1,2024-02-14,https://images.ygoprodeck.com/images/sets/LART...
758,The Lost Art Promotion 2024 A,LART,1,2024-05-22,https://images.ygoprodeck.com/images/sets/LART...

In [163]:
# Vérifier qu'aucun des sets à ajouter
# ne figure dans la collection
df_sets_common = df_sets_to_add.merge(sets_collection[columns_to_compare_sets], on=columns_to_compare_sets, how='inner')
df_sets_common

Empty DataFrame
Columns: [set_name, set_code, num_of_cards, tcg_date, set_image]
Index: []

In [164]:
# Enregistrer le DataFrame résultant dans un fichier Excel
df_sets_to_add.to_excel('d:/Projets/Code/Python/Yu-Gi-Oh-Collection/data_to_add/df_sets_to_add.xlsx', index=False)

print("Fichier df_sets_to_add.xlsx généré avec succès!")

Fichier df_sets_to_add.xlsx généré avec succès!